app_dir:
  base_output_dir: "D:/TableAnalysisTool_output" # 默认是图像文件所在文件夹
  enable_time_dir: true
  sub_cache_dir: "cache" # 缓存文件夹
  models_dir:
  log_file_dir:
  resources_dir:
    font: "resources/simfang.ttf"

app_run:
  use_device: "cuda:0"
  support_cuda:
  support_cpu:
  support_image_exts:
  enable_cache: true
  save_to_user_home: false
  print_line_result: true
  

app_models:
  paddle:
  yolo:
  tabletransformer:
  cycle_centernet:
    v1:
    v2:

app_debug:
  debug: true
  cache: false
  cut_table_cells: false
  draw_cell: true
  no_bingo_cut: false
  