app_dir:
  base_output_dir:
  sub_cache_dir:
  models_dir:
  log_file_dir:
  resources_dir:
    fonts:

app_run:
  use_device:
  support_cuda:
  support_cpu:
  support_image_exts:
  enable_cache: true
  save_to_user_home:
  

app_models:
  paddle:
  yolo:
  tabletransformer:
  cycle_centernet:

app_debug:
  cut_table_cells: true